name: unit-redis-ness

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Full Build
      run: |
        npm ci
        npm run --silent build --if-present
# https://github.com/marketplace/actions/deploy-to-github-pages
    - name: Deploy /docs folder
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: docs # The branch the action should deploy to.
        TARGET_FOLDER: docs  
        FOLDER: docs # The folder the action should deploy.
        CLEAN: true
      env:
        CI: true
